### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by joeyg** [kozmos/browser-extensions#1]
I tested this locally and it worked as a Firefox extension without any changes :) Lets package it up for distribution.

**Comment by azer** [comment]
really? that's perfect to hear. I'll do it today!

**Comment by azer** [comment]
Just submitted it for review; https://addons.mozilla.org/en-US/firefox/addon/kozmos/

Thanks a lot for letting me know Joe!

**Comment by eminx** [comment]
Page not found. What's the problem ???  I really want to avoid using Chrome...

Thanks for amazing work guys. Been looking for a tool like this ever since delicious was destroyed...

**Comment by azer** [comment]
@eminx Mozilla deleted Kozmos from their store unfortunately (they don't accept private beta apps). You can install the Firefox extension in https://getkozmos.com/settings/extension

**Comment by eminx** [comment]
Teşekkür bilader @azer ;)

With the Web extensions API, it should be pretty straightforward to fork a chrome extension to make it work on Firefox (easier said than done I know). I have previously tried but actually Firefox has a bit more of limitations especially regarding CORS issues (which I assume Kozmos uses a lot?)...

**Comment by azer** [comment]
@eminx We already provide a Firefox extension, all you need is visiting the extension page with Firefox.
